<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SceneBuilder.Application\SceneBuilder.Application.csproj" />
    <ProjectReference Include="..\SceneBuilder.Cad\SceneBuilder.Cad.csproj" />
    <ProjectReference Include="..\SceneBuilder.Infrastructure\SceneBuilder.Infrastructure.csproj" />
  </ItemGroup>

</Project>
