<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SceneBuilder.Application\SceneBuilder.Application.csproj" />
    <ProjectReference Include="..\SceneBuilder.Domain\SceneBuilder.Domain.csproj" />
    <None Include="Scripts\generate_scene.py" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
