<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SceneBuilder.Application\SceneBuilder.Application.csproj" />
    <ProjectReference Include="..\..\src\SceneBuilder.Blender\SceneBuilder.Blender.csproj" />
    <ProjectReference Include="..\..\src\SceneBuilder.Domain\SceneBuilder.Domain.csproj" />
  </ItemGroup>
</Project>
